site_name: SNT
theme:
  name: material
  language: fr
  favicon: img/favicon.png
  palette:
    primary: black
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 'Séquence 1 : Internet (I)':
    - 'Activité 1 : introduction': 'a1.md'
    - 'Résumé 1': 'r1.md'
    - 'Activité 2 : protocole TCP/IP': 'a2.md'
    - 'Résumé 2': 'r2.md'
    - 'Activité 3 : routage des paquets': 'a3.md'
    - 'Résumé 3': 'r3.md'
    - 'Activité 4 : simulation (I)': 'a4.md'
  - 'Séquence 2 : Web (I)':
    - 'Activité 5 : introduction': 'a5.md'
    - 'Résumé 5': 'r5.md'
    - 'Activité 6 : les URL': 'a6.md'
    - 'Résumé 6': 'r6.md'
    - 'Activité 7 : HTML et CSS': 'a7.md'
    - 'Résumé 7': 'r7.md'
  - 'Séquence 3 : Les RS':
    - 'Activité 8 : différents RS': 'a8.md'
    - 'Activité 9 : HTML et CSS': 'a9.md'
    - 'Résumé 9': 'r9.md'
    - 'Activité 10 : le petit monde': 'a10.md'
  - 'Séquence 4 : Web (II)':
    - 'Activité 11 : client/serveur': 'a11.md'
    - 'Résumé 11': 'r11.md'
    - 'Activité 12 : protocole HTTP': 'a12.md'
    - 'Résumé 12': 'r12.md'
    - 'Activité 13 : simulation (II)': 'a13.md'
  - 'Séquence 5 : Internet (II)':
    - 'Activité 14 : serveur DNS': 'a14.md'
    - 'Résumé 14': 'r14.md'
    - 'Activité 15 : réseaux  p2p': 'a15.md'
    - 'Résumé 15': 'r15.md'
    - 'Activité 16 : simulation (III)': 'a16.md'
  - 'Séquence 6 : Données struc':  
    - 'Activité 17 : diff données': 'a17.md'
    - 'Résumé 17': 'r17.md'
    - 'Activité 18 : trait données': 'a18.md'
    - 'Activité 19 : le cloud': 'a19.md'
    - 'Résumé 19': 'r19.md'
  - 'Séquence 7 : Web (III)':
    - 'Activité 20 : les cookies': 'a20.md'
    - 'Résumé 20': 'r20.md'
    - 'Activité 21 : moteur rech': 'a21.md'
  - 'Séquence 8 : La carotgraphie':
    - 'Activité 22 : GPS': 'a22.md'
    - 'Activité 23 : OSM': 'a23.md'
    - 'Activité 24 : catrte perso': 'a24.md'
    - 'Activité 25 : Calculs itinéraire': 'a25.md'
  - 'Séquence 9 : Photo numérique':
    - 'Activité 26 : les images': 'a26.md'
    - 'Activité 27 : capteur photo': 'a27.md'
    - 'Activité 28 : traitement image': 'a28.md'
    - 'Activité 29 : données EXIF': 'a29.md'
  - 'Séquence 10 : Info embarquée':
    - 'Activité 30 : les IHM': 'a30.md'
    - 'Activité 31 : voit auto': 'a31.md'
    - 'Activité 32 : les robots': 'a32.md'

  
  

    
