site_name: SNT
theme:
  name: material
  language: fr
  favicon: img/favicon.png
  palette:
    primary: black
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 'Séquence 1 : Internet (I)':
    - 'Activité 1 : introduction': 'a1_1.md'
    - 'Résumé 1': 'r1_1.md'
  
